# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore src dependencies
      run: dotnet restore $GITHUB_WORKSPACE/NUnitRetry.sln
      
    - name: Build src
      run: dotnet build $GITHUB_WORKSPACE/src/NUnitRetry.ReqnrollPlugin/NUnitRetry.ReqnrollPlugin.csproj --no-restore  --configuration release

    - name: Build test
      run: dotnet build $GITHUB_WORKSPACE/tests/NUnitRetry.ReqnrollPlugin.Tests/NUnitRetry.ReqnrollPlugin.Tests.csproj --no-restore  --configuration release

    - name: Test
      run: dotnet test $GITHUB_WORKSPACE/tests/NUnitRetry.ReqnrollPlugin.Tests/NUnitRetry.ReqnrollPlugin.Tests.csproj --no-restore --no-build  --configuration release
    
