# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Set version
      id: set-version
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        else
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "VERSION=${LATEST_TAG#v}-preview-${{ github.run_number }}" >> $GITHUB_ENV
        fi

    - name: Restore src
      run: dotnet restore $GITHUB_WORKSPACE/NUnitRetry.sln

    - name: Build src
      run: dotnet build $GITHUB_WORKSPACE/src/NUnitRetry.ReqnrollPlugin/NUnitRetry.ReqnrollPlugin.csproj -c Release --no-restore -p:PackageVersion=${{ env.VERSION }}

    - name: Build test
      run: dotnet build $GITHUB_WORKSPACE/tests/NUnitRetry.ReqnrollPlugin.Tests/NUnitRetry.ReqnrollPlugin.Tests.csproj -c Release --no-restore

    - name: Test
      run: dotnet test $GITHUB_WORKSPACE/tests/NUnitRetry.ReqnrollPlugin.Tests/NUnitRetry.ReqnrollPlugin.Tests.csproj -c Release --no-restore --no-build

    - name: Pack
      if: github.event_name != 'pull_request'
      run: |
        dotnet pack $GITHUB_WORKSPACE/src/NUnitRetry.ReqnrollPlugin/NUnitRetry.ReqnrollPlugin.csproj \
        -c Release \
        -p:PackageVersion=${{ env.VERSION }} \
        -p:NuspecFile=NUnitRetry.ReqnrollPlugin.nuspec \
        --no-build
      
    - name: Publish
      if: github.event_name != 'pull_request'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push $GITHUB_WORKSPACE/src/NUnitRetry.ReqnrollPlugin/bin/Release/*.nupkg \
          --api-key $NUGET_API_KEY \
          --source https://api.nuget.org/v3/index.json
      
