name: Snyk Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore $GITHUB_WORKSPACE/NUnitRetry.sln

      - name: Run Snyk
        uses: snyk/actions/dotnet@master
        with:
          args: --file=$GITHUB_WORKSPACE/NUnitRetry.sln
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}